### ISSUE TITLE
I know it says no issues here but...

### ISSUE THREAD

**Issue by austinwbest** [translate5/translate5#5]
Bug tracker?
![image](https://user-images.githubusercontent.com/8321115/164954231-1a9d7b59-c06c-4cc7-9b24-36a44e622dcc.png)

Install instructions?
![image](https://user-images.githubusercontent.com/8321115/164954242-7356c664-a2a2-4e0a-9477-4c2dc5b725d3.png)

yikes...

**Comment by thomaslauria** [comment]
This was a hosting problem and is solved now.
